### ISSUE TITLE
No such file or directory: 'tmp/nn_models'

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/alpha-automl#62]
I tried to run a pipeline search (from [tabular_classification.ipynb](https://github.com/VIDA-NYU/alpha-automl/blob/devel/examples/tabular_classification.ipynb)) and it failed with the error:
```
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/alpha_automl/pipeline_synthesis/setup_search.py", line 112, in search_pipelines
    c.learn()
  File "/opt/conda/lib/python3.9/site-packages/alpha_automl/pipeline_search/Coach.py", line 101, in learn
    self.nnet.save_checkpoint(folder=self.args.get('checkpoint'), filename='temp.pth.tar')
  File "/opt/conda/lib/python3.9/site-packages/alpha_automl/pipeline_search/pipeline/NNet.py", line 145, in save_checkpoint
    os.mkdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/nn_models'
```
To solve it, I had to create the folder `tmp` manually in the home directory of the JupyterLab installation. Does alpha-automl create this folder automatically?

**Comment by aecio** [comment]
In addition, the cell running the method `fit()` does not return when the error happens. It seems to stay blocked running indefinitely until the user interrupts the cell.

**Comment by roquelopez** [comment]
Thanks @aecio! Do you mean that it shows that error and gets 'frozen'?

**Comment by roquelopez** [comment]
Per discussion, [tempfile](https://docs.python.org/3/library/tempfile.html#module-tempfile) should be used on this.

**Comment by aecio** [comment]
In the case that the parameter `output_path` is provided (as in the linked notebook), I think we should just automatically create the directory if it does not exist.

**Comment by roquelopez** [comment]
Yes, `output_path` will be an optional param (`output_path=None`), if provided we will use/create it, otherwise use `tempfile`.
